"""empty message

Revision ID: 72259337b570
Revises: 2d791f5350d3
Create Date: 2024-09-17 18:08:32.791917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72259337b570'
down_revision = '2d791f5350d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produtos_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('orcamentos_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'produtos', ['produtos_id'], ['id'])
        batch_op.drop_column('produto_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orcamentos_ibfk_2', 'produtos', ['produto_id'], ['id'])
        batch_op.drop_column('produtos_id')

    # ### end Alembic commands ###
