"""Atualiza tabela de pessoas

Revision ID: 927cd51ab0f9
Revises: 
Create Date: 2024-09-10 19:50:56.887987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927cd51ab0f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_pessoa_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tipos_pessoa', ['tipo_pessoa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipo_pessoa_id')

    # ### end Alembic commands ###
